<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Attribution.Domain\Attribution.Domain.csproj" />
    <ProjectReference Include="..\Attribution.Application\Attribution.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="FluentMigrator" Version="8.0.1" />
    <PackageReference Include="FluentMigrator.Runner" Version="8.0.1" />
    <PackageReference Include="FluentMigrator.Runner.MySql" Version="8.0.1" />
    <PackageReference Include="MySqlConnector" Version="2.6.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
